# Project: Queue
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Node.o NodeExtendedQueue.o NodeQueue.o
LINKOBJ  = main.o Node.o NodeExtendedQueue.o NodeQueue.o
LIBS     = -L"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/lib" -L"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/include" -I"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/include" -I"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Work and study/Study/DEVC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Queue.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Node.o: Node.cpp
	$(CPP) -c Node.cpp -o Node.o $(CXXFLAGS)

NodeExtendedQueue.o: NodeExtendedQueue.cpp
	$(CPP) -c NodeExtendedQueue.cpp -o NodeExtendedQueue.o $(CXXFLAGS)

NodeQueue.o: NodeQueue.cpp
	$(CPP) -c NodeQueue.cpp -o NodeQueue.o $(CXXFLAGS)
